name: parse-lists

# update each day
on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
          
      - name: convert lists
        run: python convert.py > "cname-trackers.list"

      - name: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "updated cname-tracker list"
          git push
